openapi: 3.0.3
info:
  title: Hu$tle Hard API Documentation
  description: Displays all API documentation for the Hustle Hard Website
  contact:
    email: pbomb.nz@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: /
tags:
- name: auth
  description: Authentication activities.
- name: user
  description: Calls about user activities
- name: listing
  description: Calls about listing activities
- name: order
  description: Calls about listing order activities
- name: files
  description: Calls for file retrieval and upload.
paths:
  /users:
    get:
      tags:
      - user
      summary: Returns the authenicated user's own information.
      operationId: getUser
      responses:
        "200":
          description: Returns a JSON object of the User's Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_User'
      x-swagger-router-controller: User
    put:
      tags:
      - user
      summary: Returns the authenicated user's own information.
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity_User'
      responses:
        "200":
          description: Returns a JSON object of the User's Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_User'
      x-swagger-router-controller: User
    post:
      tags:
      - user
      summary: Registers a new user.
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity_User'
      responses:
        "200":
          description: Returns a JSON object of the User's Information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_User'
      x-swagger-router-controller: User
  /users/watchlists:
    get:
      tags:
      - user
      summary: Returns a list of listings that the user is watching.
      description: A user may watch a listing to get reminders when the listing is
        expiring and/or if they have been outbidded. This action is similar to user
        bookmarking a webpage in a browser.
      operationId: getUserListingWatchlist
      responses:
        "200":
          description: Returns a JSON Array of each listing's information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListingWatchlist'
        "401":
          description: Not Authorised
      x-swagger-router-controller: User
  /auth/login/email:
    post:
      tags:
      - auth
      operationId: authUserViaEmail
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "204":
          description: Logged in successfully.
      x-swagger-router-controller: Auth
  /auth/login/pki:
    post:
      tags:
      - auth
      operationId: authUserViaPKI
      responses:
        "204":
          description: Logged in successfully.
      x-swagger-router-controller: Auth
  /auth/logout:
    post:
      tags:
      - auth
      operationId: logoutUser
      responses:
        "204":
          description: Logged out successfully.
      x-swagger-router-controller: Auth
  /listings:
    get:
      tags:
      - listing
      summary: Retrieve a list of listings
      operationId: getListings
      parameters:
      - name: sort
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            pattern: ^[-+][a-zA-Z.]+$
            type: string
      responses:
        "200":
          description: Returns a list of listings.
        default:
          description: Default error sample response
      x-swagger-router-controller: Listing
    post:
      tags:
      - listing
      summary: Create a new listing
      operationId: createListing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity_Listing'
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Listing
  /listings/{id}:
    get:
      tags:
      - listing
      summary: Retrieve the listing that matches the specfiied ID.
      operationId: getListing
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
      responses:
        "200":
          description: A listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Listing'
        default:
          description: Default error sample response
      x-swagger-router-controller: Listing
    put:
      tags:
      - listing
      summary: Update a listing
      operationId: updateListing
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Listing
  /listing/{id}/biddings:
    get:
      tags:
      - listing
      summary: Get all biddings related to auction-based listings
      operationId: getListingBiddings
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
      responses:
        "200":
          description: All bids in descending order by date. The most recent/highest
            bid will be at the top.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_ListingBidding'
        "400":
          description: Listings that are not Auction-based will not have bidding records
      x-swagger-router-controller: Listing
    post:
      tags:
      - listing
      summary: A user can place a bidding on listing.
      operationId: createListingBid
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
      responses:
        "204":
          description: The bid has been placed.
        "400":
          description: Listings that are not Auction-based will not have bidding records
      x-swagger-router-controller: Listing
  /orders:
    get:
      tags:
      - order
      summary: Retrieves all orders of the authenticated user.
      operationId: getOrders
      responses:
        "200":
          description: Returns a order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
    post:
      tags:
      - order
      summary: Creates an order based on listing won (for auctions) or purchased (for
        MQLs).
      description: The operation is generally not performed by a user
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity_Order'
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
  /orders/{id}:
    get:
      tags:
      - order
      summary: Retrieves an order relating a the order ID suppied in the path.
      operationId: getOrderById
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Returns a order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Order'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
    put:
      tags:
      - order
      summary: Update an order by the Order ID supplied.
      operationId: updateOrder
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity_Order'
      responses:
        "200":
          description: Returns a order.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Order'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
  /ordersByConsumer/{userId}:
    get:
      tags:
      - order
      summary: Retrieves a list of orders related to a particular user whom is the
        consumer.
      operationId: getConsumerOrdersByUserId
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Returns a list of orders.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Order'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
  /ordersByProducer/{userId}:
    get:
      tags:
      - order
      summary: Retrieves a list of orders related to a particular user whom is the
        prodcuer.
      operationId: getProducerOrdersByUserId
      parameters:
      - name: userId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Returns a list of orders.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Order'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
  /ordersByListing/{listingId}:
    get:
      tags:
      - order
      summary: Retrieves a list of orders related to a particular listing.
      description: Only the producer and/or listing owner can perform this call.
      operationId: getOrdersByListingId
      parameters:
      - name: listingId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int64
      responses:
        "200":
          description: Returns a list of orders.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity_Order'
        default:
          description: Default error sample response
      x-swagger-router-controller: Order
  /files/{id}:
    get:
      tags:
      - files
      summary: Retrieves an image specified by the Image ID given.
      operationId: getFile
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: An image is returned.
          content:
            image/*:
              schema:
                type: string
                format: binary
                x-content-type: image/*
        "404":
          description: No image found with that ID
        default:
          description: Default error sample response
      x-swagger-router-controller: Files
  /files:
    post:
      tags:
      - files
      operationId: uploadFile
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: The ID (usually a hash) of the image is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        default:
          description: Default error sample response
      x-swagger-router-controller: Files
components:
  schemas:
    Type_UserAccount:
      title: Types - User Account
      pattern: ^[A-Z_]+$
      type: string
      enum:
      - EMAIL
      - PKI
    Type_UserRoles:
      title: Types - User Roles
      pattern: ^[A-Z_]+$
      type: string
      enum:
      - ADMINISTRATOR
      - USER
    Type_Listing:
      title: Types - Listing
      pattern: ^[A-Z_]+$
      type: string
      enum:
      - AUCTION
      - CLASSIFED
      - MQT
    Type_ListingCategory:
      title: Types - Listing Category
      pattern: ^[A-Z_]+$
      type: string
      enum:
      - GENERAL
      - PROPERTY
      - VEHICLE
    Category_Listing:
      title: Categories - Listing
      required:
      - category
      - id
      - type
      type: object
      properties:
        id:
          type: integer
          description: ID of the Listing Category.
          readOnly: true
        type:
          $ref: '#/components/schemas/Type_ListingCategory'
        category:
          type: string
      example:
        id: 6
        type: GENERAL
        category: category
    Entity_User:
      title: Entities - User
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        accountType:
          $ref: '#/components/schemas/Type_UserAccount'
        userName:
          type: string
        password:
          type: string
          format: password
          writeOnly: true
        givenName:
          type: string
        familyName:
          type: string
        email:
          type: string
          format: email
        address:
          type: string
        phoneNumber:
          type: string
        dateCreated:
          type: string
          format: date-time
          readOnly: true
        banned:
          type: boolean
          readOnly: true
          default: false
        bannedBy:
          type: integer
          readOnly: true
        bannedReason:
          type: string
          readOnly: true
        roles:
          type: array
          readOnly: true
          items:
            $ref: '#/components/schemas/Type_UserRoles'
      example:
        address: address
        accountType: EMAIL
        givenName: givenName
        roles:
        - ADMINISTRATOR
        - ADMINISTRATOR
        userName: userName
        bannedReason: bannedReason
        password: ""
        phoneNumber: phoneNumber
        dateCreated: 2000-01-23T04:56:07.000+00:00
        familyName: familyName
        bannedBy: 6
        id: 0
        banned: false
        email: ""
    Entity_Listing:
      title: Entities - Listing
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        type:
          $ref: '#/components/schemas/Type_Listing'
        category:
          $ref: '#/components/schemas/Category_Listing'
        status:
          type: string
        statusUpdatedBy:
          type: integer
          description: The ID of the user who updated the status.
          readOnly: true
        statusUpdatedOn:
          type: string
          format: date-time
          readOnly: true
        title:
          maxLength: 125
          type: string
        subtitle:
          maxLength: 125
          type: string
        description:
          type: string
        photo_ids:
          type: array
          items:
            type: string
          default: []
        dateCreated:
          type: string
          format: date-time
          readOnly: true
      example:
        photo_ids:
        - photo_ids
        - photo_ids
        statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
        dateCreated: 2000-01-23T04:56:07.000+00:00
        subtitle: subtitle
        description: description
        id: 0
        statusUpdatedBy: 1
        type: AUCTION
        category:
          id: 6
          type: GENERAL
          category: category
        title: title
        status: status
    Entity_ListingAuction:
      title: Entities - Listing - Auction
      type: object
      properties:
        price:
          $ref: '#/components/schemas/Entity_ListingAuction_price'
        dateExpires:
          type: string
          format: date-time
    Entity_ListingClassified:
      title: Entities - Listing - Classified
      type: object
      properties:
        price:
          $ref: '#/components/schemas/Entity_ListingClassified_price'
    Entity_ListingMQL:
      title: Entities - Listing - MQL
      required:
      - price
      - quantityAvailable
      - quantitySold
      type: object
      properties:
        price:
          type: number
          format: currency
        quantityAvailable:
          minimum: -1
          type: integer
        quantitySold:
          minimum: 0
          type: integer
    Entity_ListingPaymentOptions:
      title: Entities - Listing - Payment Options
      required:
      - method
      type: object
      properties:
        method:
          type: string
        methodDescription:
          type: string
          nullable: true
    Entity_ListingShippingOptions:
      title: Entities - Listing - Shipping Options
      required:
      - method
      - price
      type: object
      properties:
        method:
          type: string
        methodDescription:
          type: string
          nullable: true
        price:
          type: number
          format: currency
    Entity_ListingBidding:
      title: Entities - Listing Bidding
      type: array
      items:
        $ref: '#/components/schemas/Bid'
      default: []
    Entity_Order:
      title: Entities - Order
      type: object
      properties:
        user:
          readOnly: true
          allOf:
          - $ref: '#/components/schemas/Entity_User'
        deliveryAddress:
          type: string
        phoneNumberE164:
          type: string
        statusConfirmed:
          type: boolean
          default: false
        statusPaymentRecieved:
          type: boolean
          default: false
        statusProcessed:
          type: boolean
          default: false
        statusDelivered:
          type: boolean
          default: false
        statusCompleted:
          type: boolean
          default: false
        statusMessage:
          type: string
        statusUpdated:
          type: string
          format: date-time
          readOnly: true
        dateUpdated:
          type: string
          format: date-time
          readOnly: true
        dateCreated:
          type: string
          format: date-time
          readOnly: true
        items:
          $ref: '#/components/schemas/Entity_OrderItems'
      example:
        phoneNumberE164: phoneNumberE164
        statusDelivered: false
        statusMessage: statusMessage
        statusPaymentRecieved: false
        dateUpdated: 2000-01-23T04:56:07.000+00:00
        statusConfirmed: false
        statusCompleted: false
        dateCreated: 2000-01-23T04:56:07.000+00:00
        deliveryAddress: deliveryAddress
        statusProcessed: false
        user: ""
        items:
        - quantity: 0
          price: 6.02745618307040320615897144307382404804229736328125
          listing:
            photo_ids:
            - photo_ids
            - photo_ids
            statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
            dateCreated: 2000-01-23T04:56:07.000+00:00
            subtitle: subtitle
            description: description
            id: 0
            statusUpdatedBy: 1
            type: AUCTION
            category:
              id: 6
              type: GENERAL
              category: category
            title: title
            status: status
        - quantity: 0
          price: 6.02745618307040320615897144307382404804229736328125
          listing:
            photo_ids:
            - photo_ids
            - photo_ids
            statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
            dateCreated: 2000-01-23T04:56:07.000+00:00
            subtitle: subtitle
            description: description
            id: 0
            statusUpdatedBy: 1
            type: AUCTION
            category:
              id: 6
              type: GENERAL
              category: category
            title: title
            status: status
        statusUpdated: 2000-01-23T04:56:07.000+00:00
    Entity_OrderItems:
      title: Entities - Order Items
      type: array
      items:
        $ref: '#/components/schemas/Entity_OrderItems_inner'
    Entity_OrderPayment:
      type: string
    Entity_OrderShipping:
      type: string
    UserListingWatchlist:
      title: Entities - User Listing Watchlist
      type: array
      items:
        $ref: '#/components/schemas/Entity_Listing'
      default: []
    body:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    body_1:
      required:
      - bidAmount
      type: object
      properties:
        bidAmount:
          type: number
          format: currency
    inline_response_200:
      type: object
      properties:
        consumer:
          type: array
          items:
            $ref: '#/components/schemas/Entity_Order'
        producer:
          type: array
          items:
            $ref: '#/components/schemas/Entity_Order'
      example:
        producer:
        - null
        - null
        consumer:
        - phoneNumberE164: phoneNumberE164
          statusDelivered: false
          statusMessage: statusMessage
          statusPaymentRecieved: false
          dateUpdated: 2000-01-23T04:56:07.000+00:00
          statusConfirmed: false
          statusCompleted: false
          dateCreated: 2000-01-23T04:56:07.000+00:00
          deliveryAddress: deliveryAddress
          statusProcessed: false
          user: ""
          items:
          - quantity: 0
            price: 6.02745618307040320615897144307382404804229736328125
            listing:
              photo_ids:
              - photo_ids
              - photo_ids
              statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
              dateCreated: 2000-01-23T04:56:07.000+00:00
              subtitle: subtitle
              description: description
              id: 0
              statusUpdatedBy: 1
              type: AUCTION
              category:
                id: 6
                type: GENERAL
                category: category
              title: title
              status: status
          - quantity: 0
            price: 6.02745618307040320615897144307382404804229736328125
            listing:
              photo_ids:
              - photo_ids
              - photo_ids
              statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
              dateCreated: 2000-01-23T04:56:07.000+00:00
              subtitle: subtitle
              description: description
              id: 0
              statusUpdatedBy: 1
              type: AUCTION
              category:
                id: 6
                type: GENERAL
                category: category
              title: title
              status: status
          statusUpdated: 2000-01-23T04:56:07.000+00:00
        - phoneNumberE164: phoneNumberE164
          statusDelivered: false
          statusMessage: statusMessage
          statusPaymentRecieved: false
          dateUpdated: 2000-01-23T04:56:07.000+00:00
          statusConfirmed: false
          statusCompleted: false
          dateCreated: 2000-01-23T04:56:07.000+00:00
          deliveryAddress: deliveryAddress
          statusProcessed: false
          user: ""
          items:
          - quantity: 0
            price: 6.02745618307040320615897144307382404804229736328125
            listing:
              photo_ids:
              - photo_ids
              - photo_ids
              statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
              dateCreated: 2000-01-23T04:56:07.000+00:00
              subtitle: subtitle
              description: description
              id: 0
              statusUpdatedBy: 1
              type: AUCTION
              category:
                id: 6
                type: GENERAL
                category: category
              title: title
              status: status
          - quantity: 0
            price: 6.02745618307040320615897144307382404804229736328125
            listing:
              photo_ids:
              - photo_ids
              - photo_ids
              statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
              dateCreated: 2000-01-23T04:56:07.000+00:00
              subtitle: subtitle
              description: description
              id: 0
              statusUpdatedBy: 1
              type: AUCTION
              category:
                id: 6
                type: GENERAL
                category: category
              title: title
              status: status
          statusUpdated: 2000-01-23T04:56:07.000+00:00
    inline_response_200_1:
      type: object
      properties:
        id:
          type: string
          example: 1f40fc92da241694750979ee6cf582f2d5d7d28e18335de05abc54d0560e0f5302860c652bf08d560252aa5e74210546f369fbbbce8c12cfc7957b2652fe9a75.png
      example:
        id: 1f40fc92da241694750979ee6cf582f2d5d7d28e18335de05abc54d0560e0f5302860c652bf08d560252aa5e74210546f369fbbbce8c12cfc7957b2652fe9a75.png
    Entity_ListingAuction_price:
      type: object
      properties:
        buyNow:
          type: number
          format: currency
        initialReserve:
          type: number
          format: currency
    Entity_ListingClassified_price:
      type: object
      properties:
        askingPrice:
          type: number
          format: currency
        orNearestOffer:
          type: boolean
    Bid:
      title: Bid
      required:
      - bidAmount
      - dateCreated
      - username
      type: object
      properties:
        username:
          type: string
        bidAmount:
          type: number
          format: currency
        dateCreated:
          type: string
          format: date-time
          readOnly: true
      example:
        dateCreated: 2000-01-23T04:56:07.000+00:00
        bidAmount: 0.80082819046101150206595775671303272247314453125
        username: username
    Entity_OrderItems_inner:
      required:
      - price
      - quantity
      type: object
      properties:
        listing:
          $ref: '#/components/schemas/Entity_Listing'
        quantity:
          type: integer
        price:
          type: number
          format: currency
      example:
        quantity: 0
        price: 6.02745618307040320615897144307382404804229736328125
        listing:
          photo_ids:
          - photo_ids
          - photo_ids
          statusUpdatedOn: 2000-01-23T04:56:07.000+00:00
          dateCreated: 2000-01-23T04:56:07.000+00:00
          subtitle: subtitle
          description: description
          id: 0
          statusUpdatedBy: 1
          type: AUCTION
          category:
            id: 6
            type: GENERAL
            category: category
          title: title
          status: status
